### PR TITLE
WIP: Fix axisconvert for vectors.

### PR DESCRIPTION
**Pull request by danlipsa**
These are the remaining test failures on this topic, categorized.  The ones marked by an "X" seem to be fixed.

animation tests

 - [X] test_vcs_animate_boxfill.py
 - [X] test_vcs_animate_isofill.py
 - [X] test_vcs_animate_isoline.py
 - [X] test_vcs_animate_isoline_colored.py
 - [X] test_vcs_animate_isoline_text_labels.py
 - [X] test_vcs_animate_isoline_text_labels_colored.py
 - [X] test_vcs_animate_meshfill.py
 - [X] test_vcs_gms_animate_projected_plots.py

marker size

- [ ] test_vcs_1D_marker_not_shown_if_xaxis_flipped
- [ ] test_vcs_1D_mintics
- [ ] test_vcs_basic_gms_2
- [ ] test_vcs_drawLinesAndMarkersLegend
- [ ] test_vcs_markers
- [ ] test_vcs_markers_uniform_size_2
- [ ] test_vcs_taylor_2quads
- [ ] test_vcs_taylor_basic
- [ ] test_vcs_taylor_lines
- [ ] test_vcs_taylor_markers
- [ ] test_vcs_taylor_skills
- [ ] test_vcs_taylor_stdlabel
- [ ] test_vcs_taylor_template_ctl
- [ ] test_vcs_taylor_template_legend
- [ ] test_vcs_vectors_scale_options
- [ ] test_vcs_wmo_markers

style/format issue

- [X] test_vcs_flake8

widget size

- [ ] test_vcs_configurator_resize

need new/updated baseline

- [ ] test_vcs_axisconvert_2d
- [ ] test_vcs_isoline_extend_attributes
- [ ] test_vcs_isoline_width_stipple

pattern horizontal scaling issue

- [X] test_vcs_gms_patterns_hatches
- [X] test_vcs_hatches_patterns
- [X] test_vcs_large_pattern_hatch

matplotlib import error (has six version 1.7.2, needs >= 1.10)

- [ ] test_vcs_load_mpl_cmaps
- [ ] test_vcs_matplotlib_colormap

unknown (appears successful)

- [X] test_vcs_png_to_base64

vector scaling

- [ ] test_vcs_vectors_scale_options
- [ ] test_vcs_vectors_warp

### CODE REVIEW

**Comment by doutriaux1** [comment]
@danlipsa any new baselines?

**Comment by danlipsa** [comment]
@doutriaux1 This is not ready yet. I think I know what the problem is, but I am not there quite yet. Yes, I'll add new baselines once this works.

**Comment by danlipsa** [comment]
I am moving this to my laptop as we have a snow storm today and I am working from home.

**Comment by doutriaux1** [comment]
@danlipsa hopes the snow storm passes through quickly

**Comment by danlipsa** [comment]
Thanks. I am happy we'll have a bit more skiing with this snow. It has been pretty warm in the past few weeks.

**Comment by scottwittenburg** [comment]
Ok @danlipsa it seems I was mistaken in our discussion this morning.  I was led astray by the html test output tool, see (here)[https://github.com/UV-CDAT/image-compare/issues/5] for some discussion.  I now believe the opposite is true from what I said this morning, and that your change in this PR may have introduced what seems to be horizontal stretching in the animations.

I'm still looking into the issues in this topic.

**Comment by danlipsa** [comment]
@scottwittenburg Sounds good. That was my impression when I looked at the baseline differences.

**Comment by doutriaux1** [comment]
@scottwittenburg is this work in progress at this point, we're still targeting this post release, correct?

**Comment by scottwittenburg** [comment]
Yes, that's correct @charlesdoutriaux, and for the release we were just going to do #328.

**Comment by scottwittenburg** [comment]
Closing in favor of #331

**Pull request closed without merging**
