### PR TITLE
WIP: Move vtk pipelines to context2d rework fittoviewport merge master

### PR DESCRIPTION
**Pull request by scottwittenburg**
DO NOT MERGE

### CODE REVIEW

**Comment by doutriaux1** [comment]
Darn you almost got me excited here @scottwittenburg 😄

**Comment by doutriaux1** [comment]
@scottwittenburg can you setup circleci on your side so that the tests are run?

**Comment by scottwittenburg** [comment]
I guess they won't run because I made this from my fork, but won't we need the built recipes from @danlipsa first anyway?

At any rate, I just made this so I could see a summary of all the changes at one time, and github PR is convenient for that.  I was noticing that to focus on fixing some specific issues, I had commented some of the looping out of a few different tests (ugh), and I want to make sure to know all the issues I'm still facing.

**Comment by doutriaux1** [comment]
@scottwittenburg at some point (when @danlipsa conda pkg are ready) you could push this branch to the cdat org repo, to trigger the tests on circleci.

**Comment by scottwittenburg** [comment]
Sure, will do, it will be good to see what comes up there.

**Comment by scottwittenburg** [comment]
closing in favor of #369

**Pull request closed without merging**
