### PR TITLE
WIP: Context2d alpha release

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
I guess I'm still iterating on these py3 tests.  There are a bunch of things I don't recognize after all the tests now pass.  Looks like some extra checks that don't appreciate any extra debug output sent to stdout?  Any ideas @doutriaux1 or @danlipsa?  I'm going to run the full test suite in a local py3 environment and see what's going on.

**Comment by scottwittenburg** [comment]
I see.  In the case of py3, we also go into the `docs` directory and `make doctest`.  This is expecting certain output from the vcs module, and debug output in stdout is breaking that.  To me it seems kind of fragile to depend on stuff that's written to stdout, but I guess I can go ahead and create some kind of debug mode that will let me keep debugging, but allow this thing to get merged some day.

**Comment by scottwittenburg** [comment]
Update: Now I have removed the debug output, but some of those doctests still fail due to the fact that I haven't implemented postscript support.  When we discussed it, it sounded like we could leave that out for the time being, but maybe I should implement it?  The plan was to provide a wrapper around a command-line tool that would convert pdf to ps, should I go ahead and do that?

ping @doutriaux1 @danlipsa @aashish24

**Comment by scottwittenburg** [comment]
@doutriaux1 Do we also need increased (or at least not decreased) coverage?

**Comment by doutriaux1** [comment]
@scottwittenburg at that point I'm fine with it.

**Comment by scottwittenburg** [comment]
There are now ci failures for reasons unrelated to context2d.

 On the `macos_vcs_py2`, we got the wrong `vtk_cdat`.  Instead of the one from `danlipsa`, we got:

```
vtk-cdat:                      8.0.1.8.0-py27_mesalib_3                             cdat/label/nightly [mesalib      ]
```

While on `macos_vcs_py3` there seems to be a problem with a missing module:

```
b'Coverage.py warning: Module --cover-package was never imported. (module-not-imported)'
```

@doutriaux1 @muryanto1 Do either of you know how to fix these?  Or should I dig in and figure out what's going on?

**Comment by doutriaux1** [comment]
@scottwittenburg i know about the coverage one. fixing it in my jupyter pr

**Pull request merged**
