### PR TITLE
Work around axis convert for these plots until fixed

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@danlipsa @charlesdoutriaux I wasn't sure of the optimal place to put these checks/validations.  Let me know what you think.

**Comment by doutriaux1** [comment]
@scottwittenburg I think it would be better located at the time we set it, no need to go further into the code and waste time waiting for the plot call.

**Comment by scottwittenburg** [comment]
Ok, so not down in the vcsvtkbackend, but up higher in the plot abstraction?  Like in (here)[https://github.com/UV-CDAT/vcs/blob/master/vcs/streamline.py#L246]?

**Comment by doutriaux1** [comment]
yes exactly.

**Comment by scottwittenburg** [comment]
@charlesdoutriaux What should I do here?  This workaround should be ok, but the tests are failing.  When I try to go look at them, Travis says it can't find the `uv-cdat/vcs` repository.  I guess that's because of the name change to `cdat`.  Should I force push to trigger the testing again?

**Comment by doutriaux1** [comment]
@scottwittenburg I merged master in you should be good to go now. Let's wait and see.

**Comment by doutriaux1** [comment]
@scottwittenburg ready to merge if you're happy.

**Comment by scottwittenburg** [comment]
Sounds good, thanks @charlesdoutriaux!

**Pull request merged**
