### PR TITLE
Add support for the 'reference' attribute on the vector gm

### PR DESCRIPTION
**Pull request by scottwittenburg**
The 'reference' attribute has been available to read/write on
the vector graphics method, but until now has not been implemented.
Now, if it is set, the default behavior of choosing a sensible value
for the arrow length based on the screen space availabe, text size,
etc., will be overridden.  Instead the arrow length will simply be
chosen to match the reference attribute.  Hence, this feature should
be used with care, as it could result in a vector legend with either
very large or very small reference arrow.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
This addresses part of #386, by supporting the `reference` attribute of the `vector` graphics method.

Needs baselines from [here](https://github.com/CDAT/uvcdat-testdata/pull/206).

**Comment by scottwittenburg** [comment]
@danlipsa Can you take a look at this when you get a chance?  My goal was to keep your code implementing the default behavior intact (choosing an appropriate size for the vector legend arrow), while also supporting the `reference` attribute as an override.

ping @aashish24

**Comment by danlipsa** [comment]
+1. Looks good!

**Comment by scottwittenburg** [comment]
@doutriaux1 We definitely should, I was hoping that @aashish24 could eventually chime in since he wrote that code.  And the commit message you pointed me to last week (or was it the one before) didn't make sense to me.

**Comment by doutriaux1** [comment]
@danlipsa i limites this pr to mac py3 let's use it to test your work. I tried to up xcode but no luck on that end either

**Comment by doutriaux1** [comment]
@danlipsa. I would say ssh into this and try to do your manual build here against the python that was pulled. What do you think?

**Comment by doutriaux1** [comment]
@danlipsa ok so py36 works but not py37 so i think you'll need to manually build for py36. Sorry about that.

**Pull request merged**
