### PR TITLE
364 format template

### PR DESCRIPTION
**Pull request by doutriaux1**
WIP do not merge yet

### CODE REVIEW

**Comment by doutriaux1** [comment]
@lee1043 @scottwittenburg @danlipsa @aashish24 this is ready for review.

**Comment by lee1043** [comment]
@doutriaux1 looks good to me. Thanks!

**Comment by doutriaux1** [comment]
@dnadeau4 @muryanto1 it's interesting I retriggered these and they pass. I'm not sure what's different from the vcsaddons and cdms2 repos?

**Comment by doutriaux1** [comment]
@dnadeau4 @muryanto1 ok the diff is that we do not bring the compilers in here.

**Pull request merged**
