### PR TITLE
WIP: Move vtk pipelines to context2 d rework fittoviewport merge master

### PR DESCRIPTION
**Pull request by scottwittenburg**
Please DO NOT MERGE this topic yet!

### CODE REVIEW

**Comment by scottwittenburg** [comment]
Yep, there's a lot of debug output in there I still need to clean up.

**Comment by doutriaux1** [comment]
@danlipsa with my changes we got passed the mac libpng issues. Now we get ffmpeg version issue.

**Comment by scottwittenburg** [comment]
@charlesdoutriaux  I'm about to push the alpha release branch, do I need to keep that commit you pushed on this topic about "Adding prvt cdat-forge channel to bypass (maybe) cdtime issue"?

**Comment by scottwittenburg** [comment]
Closing in favor of #369

**Pull request closed without merging**
